# Generated by Django 5.0.10 on 2025-03-17 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('website_category', models.CharField(choices=[('CRYPTOCURRENCY', 'CRYPTOCURRENCY'), ('DEFI', 'DEFI'), ('NFT', 'NFT'), ('BLOCKCHAIN', 'BLOCKCHAIN'), ('METAVERSE', 'METAVERSE'), ('GAMING', 'GAMING'), ('TECHNOLOGY', 'TECHNOLOGY'), ('FINANCE', 'FINANCE')], max_length=20)),
                ('earnings', models.PositiveBigIntegerField(default='0.00')),
                ('impressions', models.PositiveBigIntegerField(default='0.00')),
                ('description', models.TextField(blank=True, null=True)),
                ('adchain_snippet', models.CharField(default='8YTEIER6yE5AQYTl1tCiF0WrAxLall6n', max_length=32, unique=True)),
                ('domain_age', models.IntegerField(blank=True, null=True)),
                ('content_quality_score', models.FloatField(blank=True, null=True)),
                ('traffic_legitimacy_score', models.FloatField(blank=True, null=True)),
                ('seo_trust_score', models.FloatField(blank=True, null=True)),
                ('overall_score', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED')], default='PENDING', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
