# Generated by Django 5.0.10 on 2025-03-17 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='websiteverification',
            old_name='website_category',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='websiteverification',
            name='adchain_snippet',
            field=models.CharField(default='pbawmIQJ2cqMrWUSAtV2IGHT82qmTV2z', max_length=32, unique=True),
        ),
    ]
