# Generated by Django 5.0.10 on 2025-03-17 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0003_alter_websiteverification_adchain_snippet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteverification',
            name='code_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='websiteverification',
            name='adchain_snippet',
            field=models.CharField(default='ABbdvX5Z2xjRAMfsHss3zVdCbxaklLtw', max_length=32, unique=True),
        ),
    ]
