# Generated by Django 5.0.10 on 2025-05-01 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0006_adunit_ad_unit_clicks_adunit_ad_unit_ctr_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adunit',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='websiteverification',
            name='adchain_snippet',
            field=models.CharField(default='N7UalgsJKnulTWvbIWYvCYs0Rl7Whqw7', max_length=32, unique=True),
        ),
    ]
