# Generated by Django 5.0.10 on 2025-05-03 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0007_adunit_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adunit',
            name='ad_unit_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adunit',
            name='ad_unit_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adunit',
            name='ad_unit_size',
            field=models.CharField(choices=[('LEADERBOARD', 'LEADERBOARD'), ('MEDIUM RECTANGLE', 'MEDIUM_RECTANGLE'), ('LARGE RECTANGLE', 'LARGE_RECTANGLE'), ('SKYSCRAPER', 'SKYSCRAPER'), ('HALF PAGE AD', 'HALF_PAGE_AD'), ('MOBILE BANNER', 'MOBILE_BANNER'), ('INTERSTITIAL', 'INTERSTITIAL'), ('VIDEO AD', 'VIDEO')], default='LEADERBOARD', max_length=20),
        ),
        migrations.AlterField(
            model_name='websiteverification',
            name='adchain_snippet',
            field=models.CharField(default='1bvuP8hQLePYlZTQ0fhd3SOXYfn3xX0I', max_length=32, unique=True),
        ),
    ]
