# Generated by Django 5.0.10 on 2025-03-14 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMINISTRATOR', 'ADMINISTRATOR'), ('PUBLISHER', 'PUBLISHER'), ('ADVERTISER', 'ADVERTISER')], default='PUBLISHER', max_length=20),
        ),
    ]
