from .base import BaseEnum

class WebsiteStatus(BaseEnum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"

class WebsiteCategory(BaseEnum):
    CRYPTOCURRENCY = "CRYPTOCURRENCY"
    DEFI = "DEFI"
    NFT = "NFT"
    BLOCKCHAIN = "BLOCKCHAIN"
    METAVERSE = "METAVERSE"
    GAMING = "GAMING"
    TECHNOLOGY = "TECHNOLOGY"
    FINANCE = "FINANCE"

class AdUnitStatus(BaseEnum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"

class AdUnitType(BaseEnum):
    BANNER = "BANNER"
    INTERSTITIAL = "INTERSTITIAL"
    NATIVE = "NATIVE"
    VIDEO = "VIDEO"
    POPUP = "POPUP"
    TEXT = "TEXT"
    LINK = "LINK"
    IMAGE = "IMAGE"
    HTML = "HTML"

class AdUnitSize(BaseEnum):
    LEADERBOARD = "LEADERBOARD"
    MEDIUM_RECTANGLE = "MEDIUM RECTANGLE"
    LARGE_RECTANGLE = "LARGE RECTANGLE"
    SKYSCRAPER = "SKYSCRAPER"
    HALF_PAGE_AD = "HALF PAGE AD"
    MOBILE_BANNER = "MOBILE BANNER"
    INTERSTITIAL = "INTERSTITIAL"
    VIDEO = "VIDEO AD"